#!/bin/sh

echo "Install dependency"
bundle install

if [ ! -d ~/.quickpod ]; then
mkdir ~/.quickpod
fi

echo "Install quickpod"
if [ -f "~/.quickpod/quickpod" ]; then 
  rm "$~/.quickpod/quickpod"
fi 

cp ./quickpod ~/.quickpod/quickpod

echo "alias quickpod='~/.quickpod/quickpod'" >> ~/.bash_profile
source ~/.bash_profile

echo "Success Installed quickpod"

# Todo check 
# if alias quickpod 2>/dev/null; then 
#   echo "installed"
# else
#   echo "Add a alias"
# fi



