#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'fileutils'
require 'cocoapods'

program :name, 'quickpod'
program :version, '0.0.1'
program :description, 'release pod quickly'

def execute(command, options = {})
    options = { :optional => false }.merge options
    abort unless (system(command) || options[:optional])
end

command :init do |c|
  c.syntax = 'quickpod init [options]'
  c.summary = ''
  c.description = '初始化fastlane环境'
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    # Do something or c.when_called Hamguy::Commands::Init
    dirname = File.join(Dir.pwd,'fastlane')
    FileUtils.mkdir_p(dirname) unless File.directory?(dirname)

    filename = File.join(dirname, 'Fastfile')
    puts filename
    FileUtils.rm(filename) unless !File.exist?(filename)

    tmppath = "/tmp/relesepod_fastlane_templete"
    execute "git clone git@gitlab.dxy.net:aspirin/relesepod_fastlane_templete.git #{tmppath}"
    execute "cp #{tmppath}/Fastfile #{filename}"
    execute "rm -rf #{tmppath}"
  end
end

command :update do |c|
  c.syntax = 'quickpod update [options]'
  c.summary = ''
  c.description = 'Update pod to target version'
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    # Do something or c.when_called quickpod::Commands::Update
    version = args[0]
    message = args[1]
    puts "target-version #{version}"
    puts "commit-message #{message}"
        
    if message
      execute "fastlane release_pod version:#{version} message:#{message}"
    else
      command = "fastlane release_pod version:#{version}" 
      execute(command)
    end
    
  end
end

